### ISSUE TITLE
Puzzle about the project name

### ISSUE THREAD

**Issue by kernel1994** [gaozhengjie/threesome#1]
To be honest, the word **threesome** has special meaning in English context.

There are some links for reference:
- [Google](https://www.google.com/search?q=threesome&oq=threesome&aqs=chrome..69i57j69i60l3&sourceid=chrome&ie=UTF-8)
- [Wikipedia](https://en.wikipedia.org/wiki/Threesome)

But, we three also can be. Whatever.

**Comment by gaozhengjie** [comment]
Although I didn't understand what English means, the picture is very vivid. I will change the project name. Do you have any suggestions? @kernel1994

**Comment by kernel1994** [comment]
> Although I didn't understand what English means, the picture is very vivid. I will change the project name. Do you have any suggestions? @kernel1994

I think this name should be retained, lol

How about you @Doooong

**Comment by gaozhengjie** [comment]
> > Although I didn't understand what English means, the picture is very vivid. I will change the project name. Do you have any suggestions? @kernel1994
> 
> I think this name should be retained, lol
> 
> How about you @Doooong

Maybe he didn't pay attention to this question at all. Let's stop talking about this issue.

**Comment by kernel1994** [comment]
I agree. Keep the name and close this issue.

**Comment by Doooong** [comment]
sorry, I forgot my email, I just watching now. About this question, I have no idea, maybe we can rename this project by Leisure_time
